version: "3.6"
services:
  redis:
    image: redis:6.2.6
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    ports:
      - 6379:6379
  mongodb:
    image : mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017

volumes:
  pgdata:
